# Generated by Django 2.0 on 2018-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ques1', models.BooleanField()),
                ('ques2', models.BooleanField()),
                ('ques3', models.BooleanField()),
                ('ques4', models.BooleanField()),
                ('ques5', models.BooleanField()),
                ('ques6', models.BooleanField()),
                ('ques7', models.BooleanField()),
                ('ques8', models.BooleanField()),
                ('ques9', models.BooleanField()),
                ('ques10', models.BooleanField()),
            ],
        ),
    ]
